// Mocks generated by Mockito 5.4.6 from annotations
// in pongstrong/test/state/tournament_data_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pongstrong/models/models.dart' as _i5;
import 'package:pongstrong/services/firestore_service/firestore_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  _i2.DocumentReference<Object?> getDoc(
    String? tournamentId,
    String? docName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoc,
          [
            tournamentId,
            docName,
          ],
        ),
        returnValue: _FakeDocumentReference_1<Object?>(
          this,
          Invocation.method(
            #getDoc,
            [
              tournamentId,
              docName,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeDocumentReference_1<Object?>(
          this,
          Invocation.method(
            #getDoc,
            [
              tournamentId,
              docName,
            ],
          ),
        ),
      ) as _i2.DocumentReference<Object?>);

  @override
  _i4.Future<void> saveTeams(
    List<_i5.Team>? teams, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTeams,
          [teams],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Team>?> loadTeams({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTeams,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<List<_i5.Team>?>.value(),
        returnValueForMissingStub: _i4.Future<List<_i5.Team>?>.value(),
      ) as _i4.Future<List<_i5.Team>?>);

  @override
  _i4.Stream<List<_i5.Team>?> teamsStream({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #teamsStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<List<_i5.Team>?>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.Team>?>.empty(),
      ) as _i4.Stream<List<_i5.Team>?>);

  @override
  _i4.Future<void> saveGroups(
    _i5.Groups? groups, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGroups,
          [groups],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Groups?> loadGroups({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadGroups,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<_i5.Groups?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Groups?>.value(),
      ) as _i4.Future<_i5.Groups?>);

  @override
  _i4.Stream<_i5.Groups?> groupsStream({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #groupsStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<_i5.Groups?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Groups?>.empty(),
      ) as _i4.Stream<_i5.Groups?>);

  @override
  _i4.Future<void> saveGruppenphase(
    _i5.Gruppenphase? gruppenphase, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGruppenphase,
          [gruppenphase],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Gruppenphase?> loadGruppenphase(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadGruppenphase,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<_i5.Gruppenphase?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Gruppenphase?>.value(),
      ) as _i4.Future<_i5.Gruppenphase?>);

  @override
  _i4.Stream<_i5.Gruppenphase?> gruppenphaseStream(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #gruppenphaseStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<_i5.Gruppenphase?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Gruppenphase?>.empty(),
      ) as _i4.Stream<_i5.Gruppenphase?>);

  @override
  _i4.Future<void> updateGruppenphaseMatch(
    String? matchId,
    int? score1,
    int? score2,
    bool? done, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGruppenphaseMatch,
          [
            matchId,
            score1,
            score2,
            done,
          ],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveTabellen(
    _i5.Tabellen? tabellen, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTabellen,
          [tabellen],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Tabellen?> loadTabellen({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadTabellen,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<_i5.Tabellen?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Tabellen?>.value(),
      ) as _i4.Future<_i5.Tabellen?>);

  @override
  _i4.Stream<_i5.Tabellen?> tabellenStream(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #tabellenStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<_i5.Tabellen?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Tabellen?>.empty(),
      ) as _i4.Stream<_i5.Tabellen?>);

  @override
  _i4.Future<void> saveKnockouts(
    _i5.Knockouts? knockouts, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKnockouts,
          [knockouts],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Knockouts?> loadKnockouts(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadKnockouts,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<_i5.Knockouts?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.Knockouts?>.value(),
      ) as _i4.Future<_i5.Knockouts?>);

  @override
  _i4.Stream<_i5.Knockouts?> knockoutsStream(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #knockoutsStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<_i5.Knockouts?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.Knockouts?>.empty(),
      ) as _i4.Stream<_i5.Knockouts?>);

  @override
  _i4.Future<void> updateKnockoutMatch(
    String? matchId,
    int? score1,
    int? score2,
    bool? done, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateKnockoutMatch,
          [
            matchId,
            score1,
            score2,
            done,
          ],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveMatchQueue(
    _i5.MatchQueue? queue, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveMatchQueue,
          [queue],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.MatchQueue?> loadMatchQueue(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMatchQueue,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<_i5.MatchQueue?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.MatchQueue?>.value(),
      ) as _i4.Future<_i5.MatchQueue?>);

  @override
  _i4.Stream<_i5.MatchQueue?> matchQueueStream(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #matchQueueStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<_i5.MatchQueue?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.MatchQueue?>.empty(),
      ) as _i4.Stream<_i5.MatchQueue?>);

  @override
  _i4.Future<void> initializeTournament(
    List<_i5.Team>? teams,
    _i5.Groups? groups, {
    String? tournamentId = 'current',
    int? tableCount = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeTournament,
          [
            teams,
            groups,
          ],
          {
            #tournamentId: tournamentId,
            #tableCount: tableCount,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> importTeamsAndGroups(
    List<_i5.Team>? teams,
    _i5.Groups? groups, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importTeamsAndGroups,
          [
            teams,
            groups,
          ],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> importTeamsOnly(
    List<_i5.Team>? teams, {
    String? tournamentId = 'current',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importTeamsOnly,
          [teams],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTournamentStyle({
    String? tournamentId = 'current',
    required String? style,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTournamentStyle,
          [],
          {
            #tournamentId: tournamentId,
            #style: style,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initializeKOOnlyTournament(
    List<_i5.Team>? teams, {
    String? tournamentId = 'current',
    int? tableCount = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeKOOnlyTournament,
          [teams],
          {
            #tournamentId: tournamentId,
            #tableCount: tableCount,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initializeRoundRobinTournament(
    List<_i5.Team>? teams, {
    String? tournamentId = 'current',
    int? tableCount = 6,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeRoundRobinTournament,
          [teams],
          {
            #tournamentId: tournamentId,
            #tableCount: tableCount,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> transitionToKnockouts({
    String? tournamentId = 'current',
    required int? numberOfGroups,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transitionToKnockouts,
          [],
          {
            #tournamentId: tournamentId,
            #numberOfGroups: numberOfGroups,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> revertToGroupPhase({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #revertToGroupPhase,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStandings({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStandings,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getTournamentMetadata(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTournamentMetadata,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Stream<Map<String, dynamic>?> tournamentMetadataStream(
          {String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #tournamentMetadataStream,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Stream<Map<String, dynamic>?>.empty(),
        returnValueForMissingStub: _i4.Stream<Map<String, dynamic>?>.empty(),
      ) as _i4.Stream<Map<String, dynamic>?>);

  @override
  _i4.Future<void> deleteTournament({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTournament,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetTournament({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetTournament,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> listTournaments() => (super.noSuchMethod(
        Invocation.method(
          #listTournaments,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<String>> listUserTournaments(String? creatorId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listUserTournaments,
          [creatorId],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> tournamentExists({String? tournamentId = 'current'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #tournamentExists,
          [],
          {#tournamentId: tournamentId},
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> createTournament({
    required String? tournamentName,
    required String? creatorId,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTournament,
          [],
          {
            #tournamentName: tournamentName,
            #creatorId: creatorId,
            #password: password,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<bool> verifyTournamentPassword(
    String? tournamentId,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyTournamentPassword,
          [
            tournamentId,
            password,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isCreator(
    String? tournamentId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCreator,
          [
            tournamentId,
            userId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> getTournamentInfo(String? tournamentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTournamentInfo,
          [tournamentId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> tournamentHasPassword(String? tournamentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #tournamentHasPassword,
          [tournamentId],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> joinTournament(
    String? tournamentId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinTournament,
          [
            tournamentId,
            userId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isParticipant(
    String? tournamentId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isParticipant,
          [
            tournamentId,
            userId,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
